config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :tweets do
    resources :likes, only:[:create, :destroy]
    member do 
      post "created_rt"
    end 
  end 

  resources :friends do 
  resources :user
  end 

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   root to: "tweets#index"
  
end

app/models/tweet.rb
class Tweet < ApplicationRecord
   validates :content, presence:true
   belongs_to :user
   has_many :likes
   has_many :retweets, class_name: "Tweet", foreign_key: "retweet_id"
   belongs_to :retweet, class_name: "Tweet", optional: true 

   scope :tweets_for_me, ->(friends_ids) {where(user_id: friends_ids)}
   
   data = Tweet.all
   @contenido = data.map{|friend|friend.content }
   
  def content_with_hashtag
  new_content = self. content.split(" ").map do |word|
    if word.include?("#")
      "<a href='/?q='#{word}'>#{word}</a>"
      end 
    end
    new_content.join(' ').html_safe
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ver_hashtag ]
  #  before_action :set_like, only: %i[ show create destroy ]
  # GET /tweets or /tweets.json
  before_action :authenticate_user!, except: %i[ index ]
  

 
  def index 
    @q = params[:q]
    
    if @q
     @tweets = Tweet.where("content ILIKE ?" , "%#{@q}%" ).page(params[:page]).paginate(page: params[:page], per_page:50)
     
    else
      tweets = user_signed_in? ? Tweet.tweets_for_me(current_user.friends.map{|friend|friend.friend_id }) : Tweet.all
      @tweets = tweets.page(params[:page]).paginate(page: params[:page], per_page:50)
    end
      
   
    # GET /tweets/1 or /tweets/1.json
  end 

  def show
  end

  def retweet
      @tweet.retweets.create(user_id: current_user, content: "")
      if @tweet.save
        redirect_to root_path
      end
    

  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
    
  end


  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    
    @tweet = Tweet.new(tweet_params)
    @tweet.user_id = current_user.id
    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweets_url, notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
          else
           format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @tweet.errors, status: :unprocessable_entity }
          end 
      end
    end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
      
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:user_id, :content, :page)
    end
  end 

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class= "text-center"> Tweets</h1>
<br>
 <form>
 <input name="q" <%= @Tweet %> >
 <button type="submit">Buscar</button>
</form>
 <br>
<table class="table table-hover">
  <thead class="thead-dark">
    <tr>
      <th scope="col">User</th>
      <th scope="col">Content</th>
      <th scope="col">Photo</th>
      <th scope="col">likes</th>
      <th scope="col">Retweets</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.user.id %></td>
        <td><%= tweet.content_with_hashtag %></td>
        <td><%= image_tag tweet.user.photo,height:100,width:100 %></td>
        <td><%= tweet.likes.count %></td>
        <td><%= link_to "Retweet" %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class = "ml-auto" >
<%= paginate @tweets, :next_label => "mostrar mas Tweets"%>
</div>
<br>
<%= link_to 'New Tweet', new_tweet_path, class:"btn btn-info text-white" %>
</div>



app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @tweet.user_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @tweet.content %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @tweet.photo %>
</p>

<p>
  <strong>Likes:</strong>
  <%= @tweet.likes.count %>
</p>


<%like = @tweet.likes.where(user: current_user) %>
<% if like.present? %>
<%= link_to 'deslike', tweet_like_path(@tweet,like.first.id) , method: :delete, class:"btn-info px-5" %>
<% else %>
<%= link_to 'like', tweet_likes_path(@tweet,like), method: :post, class:"btn-info text-white px-5" %>
<% end %>
<br>
<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>